name: description
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          short-description: ${{ github.event.repository.description }}
